// Add any additional repositories for your dependencies here

repositories {
    ivy {
        url 'https://files.vexatos.com/'
        patternLayout {
            artifact "[module]/[artifact]-[revision](-[classifier])(.[ext])"
        }
        content {
            includeGroup("TGregworks")
        }
        metadataSources {
            artifact()
        }
    }
    maven {
        name = 'ModMaven'
        url = 'https://modmaven.dev'
    }
    maven {
        name = "gt"
        url = "https://gregtech.mechaenetia.com/"
    }
    //maven {
    //	name = "CurseForge"
    //	url = "https://minecraft.curseforge.com/api/maven/"
    //}
    maven {
        name = "Jitpack"
        url = "https://jitpack.io"
    }
    maven {
        name = "CurseMaven"
        url = "https://cursemaven.com"
    }
    maven {
        name = "OpenComputers"
        url = "https://maven.cil.li/"
    }
    mavenCentral()
    mavenLocal()
}
